# model args
model: llava
model_args: pretrained=assets/weights/llava-v1.6-vicuna-7b

# task args
tasks: mmmu_val
batch_size: 1
log_samples: True
log_samples_suffix: mmmu_val

# quantization config
method: smoothquant
run_process: False # You don't need to run scale search, load the scale directly
pseudo_quant: True # if True, conduct pseudo quantization on the model, otherwise the model will stay in fp16
scale_path: run/scales/smoothquant/llava_v1.6_vicuna_7b-w8a8-samples_128.pt
w_bit: 8
a_bit: 8
alpha: 0.5

# output args
output_path: run/eval/smoothquant/llava_v1.6_vicuna_7b-w8a8-samples_128

